// Code generated by hertz generator.

package interview

import (
	interviewsapi "ai-eino-interview-agent/api/model/interviews"
	"ai-eino-interview-agent/api/response"
	"ai-eino-interview-agent/chatApp/agent/service"
	"ai-eino-interview-agent/internal/middleware"
	interviewservice "ai-eino-interview-agent/internal/service/interviews"
	"context"
	"fmt"
	"io"
	"log"
	"mime/multipart"

	"os"
	"path/filepath"
	"time"

	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"github.com/cloudwego/hertz/pkg/app"
)

// GetInterviewRecords .
// @router /api/interview/records [GET]
func GetInterviewRecords(ctx context.Context, c *app.RequestContext) {
	var err error
	var req interviewsapi.ListInterviewRecordsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Unauthorized")
		return
	}

	records, total, err := interviewservice.NewInterviewService().ListInterviewRecords(ctx, userID, req.Page, req.PageSize)
	if err != nil {
		response.ErrorFromErr(ctx, c, err)
		return
	}

	resp := new(interviewsapi.ListInterviewRecordsResponse)
	resp.Records = records
	resp.Total = total

	response.Success(ctx, c, resp)
}

// UploadResume 上传简历
// @router /api/resume/upload [POST]
func UploadResume(ctx context.Context, c *app.RequestContext) {
	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Authorization token is required")
		return
	}
	// 处理文件上传
	resumeFilePath, err := handleResumeUpload(c)
	if err != nil {
		response.BadRequest(ctx, c, err.Error())
		return
	}
	if resumeFilePath == "" {
		response.BadRequest(ctx, c, "No resume file uploaded")
		return
	}
	// 获取文件信息
	fileHeader, err := c.FormFile("resume")
	if err != nil {
		response.BadRequest(ctx, c, "Failed to get file info: "+err.Error())
		return
	}
	// 调用简历解析服务（从 session 中获取参数）
	dbResumeID, _, err := service.ParseResumeAndSave(ctx, userID, resumeFilePath, fileHeader.Size)
	if err != nil {
		log.Printf("[UploadResume] 简历解析失败: %v", err)
		response.ErrorFromErr(ctx, c, err)
		return
	}
	resp := &interviewsapi.UploadResumeResponse{
		ResumeID: int64(dbResumeID),
		Message:  "Resume uploaded and parsed successfully",
	}

	response.Success(ctx, c, resp)
}

// handleResumeUpload 处理简历文件上传
func handleResumeUpload(c *app.RequestContext) (string, error) {
	fileHeader, err := c.FormFile("resume")
	if err != nil || fileHeader == nil {
		return "", nil // 没有上传文件不是错误
	}

	// 验证文件类型
	if filepath.Ext(fileHeader.Filename) != ".pdf" {
		return "", fmt.Errorf("只支持 PDF 格式的简历文件")
	}

	// 验证文件大小
	if fileHeader.Size > 10*1024*1024 {
		return "", fmt.Errorf("文件大小不能超过 10MB")
	}

	// 打开上传的文件
	file, err := fileHeader.Open()
	if err != nil {
		return "", fmt.Errorf("无法打开上传的文件: %v", err)
	}
	defer func(file multipart.File) {
		err := file.Close()
		if err != nil {

		}
	}(file)

	// 创建项目内的文件夹
	projectRoot := filepath.Join(os.Getenv("PWD"), "uploads", "resumes")
	if err := os.MkdirAll(projectRoot, 0755); err != nil {
		return "", fmt.Errorf("无法创建上传目录: %v", err)
	}

	// 生成唯一的文件名
	timestamp := time.Now().UnixNano()
	fileName := fmt.Sprintf("resume_%d_%s", timestamp, fileHeader.Filename)
	resumeFilePath := filepath.Join(projectRoot, fileName)

	// 创建文件
	tempFile, err := os.Create(resumeFilePath)
	if err != nil {
		return "", fmt.Errorf("无法创建文件: %v", err)
	}
	defer func(tempFile *os.File) {
		err := tempFile.Close()
		if err != nil {

		}
	}(tempFile)

	// 复制文件内容
	if _, err := io.Copy(tempFile, file); err != nil {
		err := os.Remove(resumeFilePath)
		if err != nil {
			return "", err
		}
		return "", fmt.Errorf("无法保存文件: %v", err)
	}

	// 确保文件已写入磁盘
	err = tempFile.Sync()
	if err != nil {
		return "", err
	}

	return resumeFilePath, nil
}

// GetResume 获取简历详情
// @router /api/resume/:resume_id [GET]
func GetResume(ctx context.Context, c *app.RequestContext) {
	var req interviewsapi.GetResumeRequest
	err := c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Authorization token is required")
		return
	}

	resumeService := interviewservice.NewResumeService()
	data, err := resumeService.GetResumeInfoByID(ctx, uint64(req.ResumeID))
	if err != nil {
		log.Printf("[GetResume] 获取简历失败: %v", err)
		response.InternalServerError(ctx, c, "Failed to get resume: "+err.Error())
		return
	}

	// 类型断言
	resumeInfo, ok := data.(*interviewsapi.ResumeInfo)
	if !ok {
		log.Printf("[GetResume] 类型断言失败: 期望 *ResumeInfo, 实际类型: %T", data)
		response.InternalServerError(ctx, c, "Invalid resume data format")
		return
	}

	resp := &interviewsapi.GetResumeResponse{
		Resume: resumeInfo,
	}

	response.Success(ctx, c, resp)
}

// GetUserResumes 获取用户简历列表
// @router /api/resume/list [GET]
func GetUserResumes(ctx context.Context, c *app.RequestContext) {
	var req interviewsapi.GetUserResumesRequest
	err := c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Authorization token is required")
		return
	}

	page := int32(1)
	if req.Page != nil && *req.Page > 0 {
		page = *req.Page
	}

	pageSize := int32(10)
	if req.PageSize != nil && *req.PageSize > 0 {
		pageSize = *req.PageSize
	}

	resumeService := interviewservice.NewResumeService()
	data, total, err := resumeService.ListResumeInfosByUserID(ctx, userID, page, pageSize)
	if err != nil {
		log.Printf("[GetUserResumes] 获取简历列表失败: %v", err)
		response.InternalServerError(ctx, c, "Failed to get resumes: "+err.Error())
		return
	}

	// 类型断言
	resumes, ok := data.([]*interviewsapi.ResumeInfo)
	if !ok {
		log.Printf("[GetUserResumes] 类型断言失败: 期望 []*ResumeInfo, 实际类型: %T", data)
		response.InternalServerError(ctx, c, "Invalid resume data format")
		return
	}

	resp := &interviewsapi.GetUserResumesResponse{
		Resumes:  resumes,
		Total:    total,
		Page:     page,
		PageSize: pageSize,
	}

	response.Success(ctx, c, resp)
}

// GetDefaultResume 获取默认简历
// @router /api/resume/default [GET]
func GetDefaultResume(ctx context.Context, c *app.RequestContext) {
	var req interviewsapi.GetDefaultResumeRequest
	err := c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Authorization token is required")
		return
	}

	resumeService := interviewservice.NewResumeService()
	data, err := resumeService.GetDefaultResumeInfo(ctx, userID)
	if err != nil {
		log.Printf("[GetDefaultResume] 获取默认简历失败: %v", err)
		response.InternalServerError(ctx, c, "Failed to get default resume: "+err.Error())
		return
	}

	// 类型断言
	resumeInfo, ok := data.(*interviewsapi.ResumeInfo)
	if !ok {
		log.Printf("[GetDefaultResume] 类型断言失败: 期望 *ResumeInfo, 实际类型: %T", data)
		response.InternalServerError(ctx, c, "Invalid resume data format")
		return
	}

	resp := &interviewsapi.GetDefaultResumeResponse{
		Resume: resumeInfo,
	}

	response.Success(ctx, c, resp)
}

// SetDefaultResume 设置默认简历
// @router /api/resume/set-default [POST]
func SetDefaultResume(ctx context.Context, c *app.RequestContext) {
	var req interviewsapi.SetDefaultResumeRequest
	err := c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Authorization token is required")
		return
	}

	resumeService := interviewservice.NewResumeService()
	err = resumeService.SetDefaultResume(ctx, userID, uint64(req.ResumeID))
	if err != nil {
		log.Printf("[SetDefaultResume] 设置默认简历失败: %v", err)
		response.InternalServerError(ctx, c, "Failed to set default resume: "+err.Error())
		return
	}

	resp := &interviewsapi.SetDefaultResumeResponse{
		Message: "Default resume set successfully",
	}

	response.Success(ctx, c, resp)
}

// UpdateResume 更新简历
// @router /api/resume/:resume_id [PUT]
func UpdateResume(ctx context.Context, c *app.RequestContext) {
	var req interviewsapi.UpdateResumeRequest
	err := c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Authorization token is required")
		return
	}

	fileName := ""
	if req.FileName != nil {
		fileName = *req.FileName
	}

	resumeService := interviewservice.NewResumeService()
	err = resumeService.UpdateResume(ctx, uint64(req.ResumeID), fileName, "")
	if err != nil {
		log.Printf("[UpdateResume] 更新简历失败: %v", err)
		response.InternalServerError(ctx, c, "Failed to update resume: "+err.Error())
		return
	}

	resp := &interviewsapi.UpdateResumeResponse{
		Message: "Resume updated successfully",
	}

	response.Success(ctx, c, resp)
}

// DeleteResume 删除简历
// @router /api/resume/:resume_id [DELETE]
func DeleteResume(ctx context.Context, c *app.RequestContext) {
	var req interviewsapi.DeleteResumeRequest
	err := c.BindAndValidate(&req)
	if err != nil {
		response.BadRequest(ctx, c, err.Error())
		return
	}

	userID := middleware.GetUserID(c)
	if userID == 0 {
		response.Unauthorized(ctx, c, "Authorization token is required")
		return
	}

	resumeService := interviewservice.NewResumeService()
	err = resumeService.DeleteResume(ctx, userID, uint64(req.ResumeID))
	if err != nil {
		log.Printf("[DeleteResume] 删除简历失败: %v", err)
		response.InternalServerError(ctx, c, "Failed to delete resume: "+err.Error())
		return
	}

	resp := &interviewsapi.DeleteResumeResponse{
		Message: "Resume deleted successfully",
	}

	response.Success(ctx, c, resp)
}
